# Generated by Django 6.0.1 on 2026-01-19 22:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseStudy',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('vignette', models.TextField()),
                ('setting', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Highlight',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('start_index', models.IntegerField()),
                ('end_index', models.IntegerField()),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case_study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.casestudy')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('stem', models.TextField()),
                ('domain', models.CharField(choices=[('OT_EXP', 'OT Expertise'), ('CEJ_JUSTICE', 'Culture/Equity/Justice'), ('COMM_COLLAB', 'Comm & Collab'), ('PROF_RESP', 'Prof Responsibility'), ('EXCELLENCE', 'Excellence in Practice'), ('ENGAGEMENT', 'Engagement in OT')], max_length=20)),
                ('correct_label', models.CharField(max_length=1)),
                ('correct_rationale', models.TextField()),
                ('case_study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='core.casestudy')),
            ],
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_label', models.CharField(max_length=1)),
                ('confidence', models.CharField(choices=[('LOW', 'Low'), ('MED', 'Medium'), ('HIGH', 'High')], max_length=4)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_correct', models.BooleanField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True)),
                ('target_exam_date', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Distractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=1)),
                ('text', models.CharField(max_length=500)),
                ('incorrect_rationale', models.TextField(blank=True, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distractors', to='core.question')),
            ],
            options={
                'ordering': ['label'],
                'unique_together': {('question', 'label')},
            },
        ),
    ]
