# Generated by Django 6.0.1 on 2026-01-20 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_mockstudysession'),
    ]

    operations = [
        migrations.AddField(
            model_name='mockstudysession',
            name='highlights',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='mockstudysession',
            name='last_accessed',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='mockstudysession',
            name='session_history',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
