# Generated by Django 6.0.1 on 2026-01-20 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_mockstudysession_highlights_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mockstudysession',
            name='exam_config',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='mockstudysession',
            name='mode',
            field=models.CharField(default='practice', max_length=20),
        ),
        migrations.AddField(
            model_name='mockstudysession',
            name='timer_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
