# Generated by Django 6.0.1 on 2026-01-20 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_mockstudysession_exam_config_mockstudysession_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mockstudysession',
            name='next_question_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
