# Generated by Django 6.0.1 on 2026-01-20 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_mockstudysession_next_question_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='subscription_tier',
            field=models.CharField(default='free', max_length=50),
        ),
    ]
