# Generated by Django 6.0.1 on 2026-01-21 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_userprofile_email_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='trial_start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
