# Generated by Django 6.0.4 on 2026-06-25 23:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_userprofile_trial_start_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankCase',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('vignette', models.TextField()),
                ('setting', models.CharField(max_length=120)),
                ('domain', models.CharField(choices=[('OT_EXP', 'OT Expertise'), ('CEJ_JUSTICE', 'Culture/Equity/Justice'), ('COMM_COLLAB', 'Comm & Collab'), ('PROF_RESP', 'Prof Responsibility'), ('EXCELLENCE', 'Excellence in Practice'), ('ENGAGEMENT', 'Engagement in OT')], max_length=20)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('provenance', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='BankQuestion',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('domain', models.CharField(choices=[('OT_EXP', 'OT Expertise'), ('CEJ_JUSTICE', 'Culture/Equity/Justice'), ('COMM_COLLAB', 'Comm & Collab'), ('PROF_RESP', 'Prof Responsibility'), ('EXCELLENCE', 'Excellence in Practice'), ('ENGAGEMENT', 'Engagement in OT')], max_length=20)),
                ('difficulty', models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], max_length=10)),
                ('format', models.CharField(choices=[('standalone', 'Standalone'), ('case', 'Case-based')], default='standalone', max_length=12)),
                ('stem', models.TextField()),
                ('correct_label', models.CharField(max_length=1)),
                ('correct_rationale', models.TextField()),
                ('topic', models.CharField(blank=True, max_length=160)),
                ('cognitive_level', models.CharField(choices=[('recall', 'Recall'), ('application', 'Application'), ('analysis', 'Analysis')], default='application', max_length=12)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('needs_review', 'Needs Review'), ('rejected', 'Rejected')], db_index=True, default='draft', max_length=12)),
                ('provenance', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='core.bankcase')),
            ],
            options={
                'ordering': ['domain', 'difficulty'],
            },
        ),
        migrations.CreateModel(
            name='BankDistractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=1)),
                ('text', models.CharField(max_length=600)),
                ('incorrect_rationale', models.TextField(blank=True, null=True)),
                ('bank_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distractors', to='core.bankquestion')),
            ],
            options={
                'ordering': ['label'],
            },
        ),
        migrations.AddIndex(
            model_name='bankquestion',
            index=models.Index(fields=['domain', 'difficulty', 'status'], name='core_bankqu_domain_ad9fc3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='bankdistractor',
            unique_together={('bank_question', 'label')},
        ),
    ]
