# Generated by Django 6.0.4 on 2026-06-26 00:08

from django.db import migrations, models


# Remap the legacy cognitive taxonomy (recall/analysis) to the NOTCE 2026
# Resource Manual wording (knowledge/critical thinking). This runs AFTER the
# AlterField widens the column to varchar(20); 'critical_thinking' would not fit
# the old varchar(12). 'application' is unchanged.
COGNITIVE_REMAP = {'recall': 'knowledge', 'analysis': 'critical_thinking'}


def remap_cognitive_forward(apps, schema_editor):
    BankQuestion = apps.get_model('core', 'BankQuestion')
    for old, new in COGNITIVE_REMAP.items():
        BankQuestion.objects.filter(cognitive_level=old).update(cognitive_level=new)


def remap_cognitive_backward(apps, schema_editor):
    BankQuestion = apps.get_model('core', 'BankQuestion')
    for old, new in COGNITIVE_REMAP.items():
        BankQuestion.objects.filter(cognitive_level=new).update(cognitive_level=old)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_bankcase_bankquestion_bankdistractor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankcase',
            name='age_group',
            field=models.CharField(blank=True, choices=[('child', 'Child'), ('adolescent', 'Adolescent'), ('adult', 'Adult'), ('older_adult', 'Older Adult')], default='', max_length=16),
        ),
        migrations.AddField(
            model_name='bankcase',
            name='client_type',
            field=models.CharField(blank=True, choices=[('individual', 'Individual'), ('family', 'Family'), ('group', 'Group'), ('community', 'Community'), ('organization', 'Organization'), ('population', 'Population')], default='', max_length=16),
        ),
        migrations.AddField(
            model_name='bankcase',
            name='diagnosis_category',
            field=models.CharField(blank=True, choices=[('neurological', 'Neurological'), ('musculoskeletal', 'Musculoskeletal'), ('mental_health', 'Mental Health'), ('general_medical', 'General Medical')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='bankcase',
            name='practice_setting',
            field=models.CharField(blank=True, choices=[('rehab_centre', 'Rehabilitation Centre'), ('ltc', 'Long-Term Care Facility'), ('pediatric', 'Pediatric Facility'), ('home_care', 'Home Care'), ('community_agency', 'Community Agency'), ('regulatory_gov', 'Regulatory/Government Office'), ('criminal_justice', 'Criminal Justice'), ('workplace', 'Workplace'), ('education', 'Education System'), ('hospital_inpatient', 'Hospital Inpatient'), ('hospital_outpatient', 'Hospital Outpatient'), ('mh_inpatient', 'Mental Health Facility Inpatient'), ('mh_outpatient', 'Mental Health Facility Outpatient'), ('insurance', 'Insurance (WSIB/WCB/Auto)')], default='', max_length=24),
        ),
        migrations.AddField(
            model_name='bankcase',
            name='pronouns',
            field=models.CharField(blank=True, choices=[('he', 'He/Him'), ('she', 'She/Her'), ('they', 'They/Them'), ('non_binary', 'Non-binary'), ('transgender', 'Transgender')], default='', max_length=16),
        ),
        migrations.AddField(
            model_name='bankcase',
            name='representation',
            field=models.CharField(blank=True, choices=[('not_specified', 'Not specified'), ('black', 'Black'), ('indigenous', 'Indigenous'), ('person_of_colour', 'Person of Colour')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='bankquestion',
            name='age_group',
            field=models.CharField(blank=True, choices=[('child', 'Child'), ('adolescent', 'Adolescent'), ('adult', 'Adult'), ('older_adult', 'Older Adult')], default='', max_length=16),
        ),
        migrations.AddField(
            model_name='bankquestion',
            name='client_type',
            field=models.CharField(blank=True, choices=[('individual', 'Individual'), ('family', 'Family'), ('group', 'Group'), ('community', 'Community'), ('organization', 'Organization'), ('population', 'Population')], default='', max_length=16),
        ),
        migrations.AddField(
            model_name='bankquestion',
            name='diagnosis_category',
            field=models.CharField(blank=True, choices=[('neurological', 'Neurological'), ('musculoskeletal', 'Musculoskeletal'), ('mental_health', 'Mental Health'), ('general_medical', 'General Medical')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='bankquestion',
            name='practice_setting',
            field=models.CharField(blank=True, choices=[('rehab_centre', 'Rehabilitation Centre'), ('ltc', 'Long-Term Care Facility'), ('pediatric', 'Pediatric Facility'), ('home_care', 'Home Care'), ('community_agency', 'Community Agency'), ('regulatory_gov', 'Regulatory/Government Office'), ('criminal_justice', 'Criminal Justice'), ('workplace', 'Workplace'), ('education', 'Education System'), ('hospital_inpatient', 'Hospital Inpatient'), ('hospital_outpatient', 'Hospital Outpatient'), ('mh_inpatient', 'Mental Health Facility Inpatient'), ('mh_outpatient', 'Mental Health Facility Outpatient'), ('insurance', 'Insurance (WSIB/WCB/Auto)')], default='', max_length=24),
        ),
        migrations.AddField(
            model_name='bankquestion',
            name='pronouns',
            field=models.CharField(blank=True, choices=[('he', 'He/Him'), ('she', 'She/Her'), ('they', 'They/Them'), ('non_binary', 'Non-binary'), ('transgender', 'Transgender')], default='', max_length=16),
        ),
        migrations.AddField(
            model_name='bankquestion',
            name='representation',
            field=models.CharField(blank=True, choices=[('not_specified', 'Not specified'), ('black', 'Black'), ('indigenous', 'Indigenous'), ('person_of_colour', 'Person of Colour')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='bankquestion',
            name='cognitive_level',
            field=models.CharField(choices=[('knowledge', 'Knowledge'), ('application', 'Application'), ('critical_thinking', 'Critical Thinking')], default='application', max_length=20),
        ),
        # Runs last: column is now varchar(20) so 'critical_thinking' fits.
        migrations.RunPython(remap_cognitive_forward, remap_cognitive_backward),
    ]
