# Generated by Django 6.0.4 on 2026-06-26 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_blueprint_descriptors'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankquestion',
            name='core_concept',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='bankquestion',
            name='explain_differently',
            field=models.TextField(blank=True, default=''),
        ),
    ]
