# Generated by Django 6.0.1 on 2026-06-26 16:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_organization_mockstudysession_organization_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_key', models.CharField(max_length=80)),
                ('source', models.CharField(choices=[('case', 'Case'), ('bank', 'Bank')], max_length=8)),
                ('domain', models.CharField(blank=True, default='', max_length=20)),
                ('box', models.PositiveSmallIntegerField(default=0)),
                ('due_at', models.DateTimeField(db_index=True)),
                ('last_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reps', models.PositiveIntegerField(default=0)),
                ('lapses', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'due_at'], name='core_review_user_id_77087d_idx')],
                'unique_together': {('user', 'item_key')},
            },
        ),
    ]
