# Generated by Django 6.0.1 on 2026-06-26 16:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_reviewitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CohortAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('domain', models.CharField(blank=True, choices=[('OT_EXP', 'OT Expertise'), ('CEJ_JUSTICE', 'Culture/Equity/Justice'), ('COMM_COLLAB', 'Comm & Collab'), ('PROF_RESP', 'Prof Responsibility'), ('EXCELLENCE', 'Excellence in Practice'), ('ENGAGEMENT', 'Engagement in OT')], default='', max_length=20)),
                ('target_questions', models.PositiveIntegerField(default=20)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('note', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_assignments', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='core.organization')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
